### PR TITLE
Package refresh 2021 spring: bump package and drop EOL LTS

### PR DESCRIPTION
**Pull request by AdrieanKhisbe**
Package refresh with updated dependencies, and drop support of both node 8 and node 10.
As a result would only be mergeable at this month end, [once node 16 is released](https://nodejs.org/en/about/releases/)

Reformat is due to bump of prettier to v2

See discussion in #56 pull request

### CODE REVIEW

**Comment by AdrieanKhisbe** [comment]
@azeemba I added a commit to relaunch test as 16 was released.

However tests results dont' appears here, you might need to log to travis.org and perform migration to travis.com
https://travis-ci.org/github/azeemba/eslint-plugin-json

**Comment by azeemba** [comment]
> However tests results dont' appears here, you might need to log to travis.org and perform migration to travis.com
> https://travis-ci.org/github/azeemba/eslint-plugin-json

Thanks! I will create an issue for us to migrate to actions.

**Comment by AdrieanKhisbe** [comment]
Okey @azeemba, waiting the config to be made, org to com migration is supposed to rather easy: 
https://docs.travis-ci.com/user/migrate/open-source-repository-migration

**Comment by AdrieanKhisbe** [comment]
Looks like CI status is here, and node 16 is out.
So whenever you're ok @azeemba :)

**Comment by azeemba** [comment]
Thanks for the work @AdrieanKhisbe! [v3.0.0](https://www.npmjs.com/package/eslint-plugin-json/v/3.0.0) has been released!

**Pull request merged**
