### PR TITLE
Create rule schema to support "allowComments"

### PR DESCRIPTION
**Pull request by azeemba**
eslint v9 made schema mandatory for options supported by rules:
https://eslint.org/docs/latest/extend/custom-rules#options-schemas

Previously we didn't use the meta object on the rules so now we create the meta object and populate the `schema` property.

Thanks to @BePo65 for providing context, docs and the schema itself.

### CODE REVIEW

**Comment by azeemba** [comment]
@Standard8 and @BePo65 let me know if you have any thoughts on this PR.

I plan to land it during the week and push a new major release next weekend.

**Comment by BePo65** [comment]
The pr looks good. Only test coverage for lines 58-62 and 150-154 is missing.

So I am trying to add 1 or more tests for the `allowComments` setting.
The problem is that here we do not test rules, but a configuration setting. I'm trying to find out, how to add configuration settings for the tested rule.

Perhaps you could give me a hint, where in the `unit.test.js` file config settings can be 'sent' to the plugin; otherwise it will take me a little bit longer (I don't call me lazy, but just efficient 😄 ). Any help appreciated.

**Comment by Standard8** [comment]
> Perhaps you could give me a hint, where in the `unit.test.js` file config settings can be 'sent' to the plugin; otherwise it will take me a little bit longer (I don't call me lazy, but just efficient 😄 ). Any help appreciated.

I don't think there is an easy way. The unit tests appear to be testing only the processor, not from the rule level (i.e. they're not using [`RuleTester`](https://eslint.org/docs/latest/integrate/nodejs-api#ruletester)).

However, I would note that the integration tests are [covering comments](https://github.com/azeemba/eslint-plugin-json/blob/8a999c67cd0874a296e36ff4cfd12047a002bfe8/test/integration.test.js#L98-L129), it just doesn't show up on the code coverage.

**Comment by BePo65** [comment]
So perhaps it would be the best solution to add rules test (with coverage) in a new pr.

That would give me a little bit more time for this topic (at the moment I'm quite busy in my main project). But nevertheless I would like to get a deeper understanding of custom eslint rules anyway and testing the rule algorithm (with coverage) would be a good reason to do that.

@azeemba is this an acceptable way you are willing to live with?

**Comment by BePo65** [comment]
Prepared a pr (extending this pr) that adds tests for the rules to the unit tests. These tests bring coverage back to 100%.

Should we add this modification to this pr here or create a new pr (or simply drop the idea 😄 )?

**Comment by azeemba** [comment]
@BePo65 thanks for looking into it! A separate PR would be awesome.

I will go ahead and merge this PR for now and prep a release.

**Pull request merged**
