### PR TITLE
Package refresh 2021 summer

### PR DESCRIPTION
**Pull request by AdrieanKhisbe**
Updated dependencies to address the different vulns (cf current batch of dependabot PRs #59 to #62)

### CODE REVIEW

**Comment by azeemba** [comment]
Thanks a lot @AdrieanKhisbe! I will have a look in a day or two.

**Comment by AdrieanKhisbe** [comment]
No hurry @azeemba =)

**Review by azeemba — APPROVED** [review]
Looks good! Thanks!

**Comment by azeemba** [comment]
Published as [3.1.0](https://www.npmjs.com/package/eslint-plugin-json/v/3.1.0). Thanks again!

**Comment by AdrieanKhisbe** [comment]
You're welcome @azeemba  🙂

Unfortunately it seems I forgot to audit fix the eslint 6 cf #59 🙈

**Pull request merged**
