### PR TITLE
Use eslint, not jshint, to test input

### PR DESCRIPTION
**Pull request by vegardok**

### CODE REVIEW

**Comment by vegardok** [comment]
I started with this plugin but ended up with something completely different. I primarily use eslint for json because jscs is merged with eslint and this allows me to do that.

**Comment by azeemba** [comment]
This is going to cause issues with things that are valid JS but not valid json right? For example, trailing commas and keys being in quotes.

**Comment by vegardok** [comment]
Yes, you leaves you free to set up whatever rules you want, e.g `comma-dangle` and `quite-props`.

**Comment by vegardok** [comment]
I also made a custom eslint rule to check of the input is parsable, https://github.com/vegardok/eslint-plugin-json/commit/47bd4d2067bd1562fd5fefafa59b5377d6eb758c

**Comment by vegardok** [comment]
It would be great if you could indicate if you are interested in this PR, if not then I'll just use my own fork.

**Comment by azeemba** [comment]
Thanks for adding the parseable check. That was really my main concern.

I will just test out your changes for a little bit and if that looks good
then I will accept it.

**Comment by azeemba** [comment]
So you mentioned vegardok@47bd4d2 but it seems that that commit is not part of this review?

Additionally, I think we should ONLY do that change. We shouldn't try to process the JSON against the normal `.eslintrc` rules since some folks may want `comma-dangle` in their JS but obviously can't in JSON. So the two options I am thinking we have are:

 - Only add JSON.parse as a new rule
 - Figure out a way to allow different eslint confg for JSON vs regular JS

**Comment by vegardok** [comment]
It's not a problem to use different sets of rules for different files, ether by using [configuration cascading](http://eslint.org/docs/user-guide/configuring#configuration-cascading-and-hierarchy) or the `--ext` parameter. 

I don't think I can add the commit to this PR, but PR should do as few things as possible so that's really a good thing. I can make another PR afterwards.

**Comment by azeemba** [comment]
Cascading doesn't really help if users have JSON and js files in the same
folder, which is pretty common.

`--ext` doesn't fix the problem entirely since this means we will force
users to have two different eslint commands instead of just one to lint
both JSON and js files.

Commits should be as small as possible but they should not break things
which I believe the current commit is doing.

On Jan 2, 2017 6:26 AM, "vegardok" <notifications@github.com> wrote:

It's not a problem to use different sets of rules for different files,
ether by using configuration cascading
<http://eslint.org/docs/user-guide/configuring#configuration-cascading-and-hierarchy>
or the --ext parameter.

I don't think I can add the commit to this PR, but PR should do as few
things as possible so that's really a good thing. I can make another PR
afterwards.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/azeemba/eslint-plugin-json/pull/9#issuecomment-269960633>,
or mute the thread

**Comment by azeemba** [comment]
Unfortunately I will have to close this. 
I appreciate the effort but its important that JSON linting continues working independent of what `.eslintrc` rules exist for JS since JSON is way stricter than JS.

**Pull request closed without merging**
