### PR TITLE
Use ESLint to validate and fix indentation

### PR DESCRIPTION
**Pull request by edg2s**

### CODE REVIEW

**Comment by AdrieanKhisbe** [comment]
Hello @edg2s :)
Was just wondering if you closed you PR because you consider #39 would fulfill your need, or if there was any other reason.

**Comment by edg2s** [comment]
This was an alternate approach to #40 which included the ability to fix errors by using a similar approach to #39, however the limitation is that it uses the same rules as your regular linter.

**Comment by edg2s** [comment]
This approach on its own is very sensible, and with a proper config of "overrides" could work well, but it essentially says "treat this file as JS, and continue to lint as normal (with some custom changes for quote style etc.)", but the API for this plugin is to introduce new rules e.g. "plugin:json/foo" so I'm not sure it would be appropriate for this repo.

**Comment by edg2s** [comment]
#40 on the other hand behaves more like the JSON validation rules in the plugin, namely executing a new lint run for each file, and piping through any errors.

The downside of #40 is it doesn't support fixing.

**Pull request closed without merging**
