### PR TITLE
Package refresh 02 2020

### PR DESCRIPTION
**Pull request by AdrieanKhisbe**
Bump license years, and all dependencies (Superseed and Closes #33 @dependabot vuln fix PR)

### CODE REVIEW

**Comment by AdrieanKhisbe** [comment]
Was planning to do a minor release after merging this pr.
What do you think about this @azeemba ? :)

**Comment by AdrieanKhisbe** [comment]
@azeemba I made the version bump via 40ce1e6269ec21ce2808dec6ad7a5117930606c8, but I couldn't publish. (I don't have persions on npm)
Could you do it? :)

**Comment by azeemba** [comment]
Will do so later today. Thanks for the update!

**Comment by azeemba** [comment]
@AdrieanKhisbe [v2.1.0](https://www.npmjs.com/package/eslint-plugin-json/v/2.1.0) has been released!

**Comment by AdrieanKhisbe** [comment]
Awesome!
thanks @azeemba =)

**Pull request merged**
