### PR TITLE
 Update all third party dependencies to latest version

### PR DESCRIPTION
**Pull request by thethomaseffect**
I did this to see if it would resolve the JSHint lodash security warning but it sadly doesn't. However, it does fix a bunch of other warnings so it's still worth merging!

### CODE REVIEW

**Comment by azeemba** [comment]
Thanks a lot for the PR.
jshint just landed an upgrade a few days ago: https://github.com/jshint/jshint/commit/bcb3b23336600db183e8f37c6869039c0b25f4c4

Hopefully they will push a new release soon and we can upgrade all the dependencies in one go?

**Comment by azeemba** [comment]
Also if you merge/rebase the travis CI should start working.

**Comment by thethomaseffect** [comment]
Makes sense, and merged upstream changes, CI all good now

**Comment by Empact** [comment]
@thethomaseffect please update jshint also, it's the source of the security warning. Their latest is 2.9.5. https://www.npmjs.com/package/jshint

**Comment by azeemba** [comment]
As described above, jshint hasn't published a new version with the fix.
2.9.5 was published a year ago.

**Comment by thethomaseffect** [comment]
The patch version will need to change for the next release regardless, by the sounds of it this PR will just sit pretty until that JSHint update is released. If something else is changed in the meantime the version can be fixed before this is released at the same time the newer JSHint is added.

**Pull request merged**
